### ISSUE TITLE
table names with double quotes not properly translated 

### ISSUE THREAD

**Issue by MarcoVugts** [duneanalytics/harmonizer#40]
It seems like table names with double quotes are not propery translated, for example:

erc20."ERC20_evt_Transfer"  --> erc20_optimism.ERC20_evt_Transfer

Tried to look into the python code but not sure how to fix it.

**Comment by vegarsti** [comment]
Hey Marco! Thanks for reporting.
Do you have an example query on Dune, and what the expected output should be?
Since the table `erc20_optimism.ERC20_evt_Transfer` doesn't exist, did you mean that it should be translated to `erc20_optimism.evt_Transfer`?

**Comment by MarcoVugts** [comment]
I migrated it, but it was from the Optimism 2.0 engine, so also might have to do with that? 
But yes indeed the translation should be erc20_optimism.evt_Transfer, but it is translated to erc20_optimism.ERC20_evt_Transfer

**Comment by vegarsti** [comment]
Fix released and deployed now, let me know if you see any related issues!
