### ISSUE TITLE
Spark requires length when casting to VARCHAR, but doesn't truncate string

### ISSUE THREAD

**Issue by vegarsti** [duneanalytics/harmonizer#74]
But when transpiled into Trino, the string is truncated.

A suggestion PR was opened in #70, but this is also fixed upstream in https://github.com/tobymao/sqlglot/pull/1730, so when that is released, this will be fixed.

**Comment by GeorgeSittas** [comment]
The fix has been deployed with v15.1.0

**Comment by vegarsti** [comment]
> The fix has been deployed with v15.1.0

Great, thanks!
